from gui_commands.center_video import CenterVideo
from gui_commands.create_dataset import CreateDataset
from gui_commands.front_video import FrontVideo
from gui_commands.analytics_tab import AnalyticsTab
from gui_commands.advanced_analytics_tab import AdvancedAnalyticsTab
from gui_commands.main_window import MainWindow
from visualizations.line_chart_visualization import Advanced_Analytics_Line_Chart_Visualization